export {
  getProdDb,
  closeProdDb,
  getTestDb,
  runMigrations,
  type Db,
} from "./client.js";

export * as schema from "./schema.js";

// Brand-kit renderer (pure)
export {
  renderBrandKit,
  type BrandKitMeta,
  type RenderedBrandFile,
} from "./brand-kit.js";

// Convenience re-exports of all table objects
export {
  leads,
  brandProfiles,
  siteInventories,
  competitors,
  generatedSites,
  outreachMessages,
  pipelineJobs,
  inboundInquiries,
  workerHeartbeats,
  emailTemplates,
  sequenceSteps,
  leadActivities,
  blogPosts,
  // Self-serve platform (AI Marketing)
  brands,
  brandKitFiles,
  brandKitAssets,
  profiles,
  operateProjects,
  // Enum value arrays
  leadStatusValues,
  blogPostStatusValues,
  generatedSiteCreatedViaValues,
  outreachDirectionValues,
  outreachStatusValues,
  pipelineJobStatusValues,
  inboundInquiryStatusValues,
  logoSourceValues,
  salesStageValues,
  sequenceAngleValues,
  sequenceStepStatusValues,
  activityTypeValues,
  brandStatusValues,
  brandKitFileTypeValues,
  brandKitAssetRoleValues,
  brandKitAssetSourceValues,
  userRoleValues,
  operateProjectStatusValues,
  // Types
  type BrandSignals,
  type BrandStatus,
  type BrandKitFileType,
  type Brand,
  type NewBrand,
  type BrandKitFile,
  type NewBrandKitFile,
  type BrandKitAsset,
  type Profile,
  type NewProfile,
  type OperateProject,
  type NewOperateProject,
  type OperateIntake,
  type UserRole,
  type LeadStatus,
  type LogoSource,
  type GeneratedSiteCreatedVia,
  type OutreachDirection,
  type OutreachStatus,
  type PipelineJobStatus,
  type InboundInquiryStatus,
  type InventoryPage,
  type InventoryAsset,
  type WorkerHostInfo,
  type SalesStage,
  type SequenceAngle,
  type SequenceStepStatus,
  type ActivityType,
  type BlogPostStatus,
  type BlogDiagram,
  type BlogPost,
  type NewBlogPost,
} from "./schema.js";
