/**
 * queue.ts — pipeline_jobs helpers for local-worker.
 *
 * Mirrors apps/admin/lib/queue.ts. We re-implement here rather than import
 * across apps because apps/admin is a Next.js bundle; importing its files
 * from a plain Node process pulls in Next.js types and "next/server"
 * deps that wouldn't resolve. The functions are small, identical, and
 * tested by the local-worker tests independently of admin.
 *
 * IMPORTANT: keep this file in lockstep with the admin copy — the queue
 * semantics (FOR UPDATE SKIP LOCKED, attemptCount bump) are load-bearing
 * for multi-worker correctness.
 */

import { eq, and, lte } from "drizzle-orm";
import { pipelineJobs } from "@atelier/db";
import { nanoid } from "nanoid";
import type { Db } from "@atelier/db";

export interface EnqueueArgs {
  leadId?: string | null;
  step: string;
  payload: Record<string, unknown>;
  notBefore?: Date;
}

export async function enqueue(db: Db, args: EnqueueArgs): Promise<string> {
  const id = nanoid();
  await db.insert(pipelineJobs).values({
    id,
    leadId: args.leadId ?? null,
    pipelineStep: args.step,
    status: "queued",
    payload: args.payload,
    attemptCount: 0,
    ...(args.notBefore ? { createdAt: args.notBefore } : {}),
  });
  return id;
}

/**
 * Claim the next queued job for one of the given steps. Uses `FOR UPDATE
 * SKIP LOCKED` so two workers polling concurrently never claim the same
 * row. Returns `null` if the queue is empty.
 *
 * Local-worker passes `steps = ["generate", "deploy"]` so we accept an
 * array. Postgres' `IN (?, ?)` is generated by Drizzle's `inArray` but
 * we keep this simple by issuing per-step SELECTs ordered by createdAt
 * inside the same transaction — at most 2 steps, so 2 SELECTs is fine.
 */
export async function claimNext(
  db: Db,
  steps: string[],
  _workerName: string,
) {
  return db.transaction(async (tx) => {
    const now = new Date();

    // Try each step in order — first match wins. This gives `generate`
    // priority over `deploy` when both are queued, which matches the
    // pipeline's natural ordering (deploy follows generate).
    for (const step of steps) {
      const candidates = await tx
        .select()
        .from(pipelineJobs)
        .where(
          and(
            eq(pipelineJobs.status, "queued"),
            eq(pipelineJobs.pipelineStep, step),
            lte(pipelineJobs.createdAt, now),
          ),
        )
        .orderBy(pipelineJobs.createdAt)
        .limit(1)
        .for("update", { skipLocked: true });

      const job = candidates[0];
      if (!job) continue;

      await tx
        .update(pipelineJobs)
        .set({
          status: "running",
          startedAt: now,
          lastHeartbeatAt: now,
          attemptCount: (job.attemptCount ?? 0) + 1,
        })
        .where(eq(pipelineJobs.id, job.id));

      return { ...job, status: "running" as const };
    }
    return null;
  });
}

export async function heartbeat(db: Db, jobId: string) {
  await db
    .update(pipelineJobs)
    .set({ lastHeartbeatAt: new Date() })
    .where(eq(pipelineJobs.id, jobId));
}

export async function completeJob(db: Db, jobId: string) {
  await db
    .update(pipelineJobs)
    .set({ status: "succeeded", finishedAt: new Date() })
    .where(eq(pipelineJobs.id, jobId));
}

export async function failJob(db: Db, jobId: string, error: string) {
  await db
    .update(pipelineJobs)
    .set({ status: "failed", finishedAt: new Date(), errorMessage: error })
    .where(eq(pipelineJobs.id, jobId));
}
