-- RLS + Supabase Auth wiring for the self-serve platform.
--
-- Apply ONCE, AFTER the Drizzle migrations (>= 0008) AND after Supabase Auth is
-- enabled. This is intentionally NOT part of the Drizzle journal: cross-schema
-- FKs (auth.users), triggers, and RLS policies can't be generated by drizzle-kit.
--
-- The WORKER and ADMIN use the service_role key, which BYPASSES RLS by design,
-- so admin oversight across all customers needs no extra policies.
-- The existing lead-gen tables (leads, brand_profiles, ...) are intentionally
-- left without RLS: customers never query them directly; only service role does.

-- 1. profiles <-> auth.users ---------------------------------------------------
alter table public.profiles
  add constraint profiles_id_fkey
  foreign key (id) references auth.users(id) on delete cascade;

-- Auto-create a profile row on signup (role defaults to 'customer').
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Helper: is the current request an admin? (used in policies / app guards)
create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$;

-- 2. enable RLS ----------------------------------------------------------------
alter table public.profiles          enable row level security;
alter table public.brands            enable row level security;
alter table public.brand_kit_files   enable row level security;
alter table public.brand_kit_assets  enable row level security;
alter table public.operate_projects  enable row level security;

-- 3. profiles policies ---------------------------------------------------------
create policy "profiles_select_own_or_admin" on public.profiles
  for select using (id = auth.uid() or public.is_admin());
create policy "profiles_update_own" on public.profiles
  for update using (id = auth.uid()) with check (id = auth.uid());

-- 4. brands (owner_user_id = auth.uid()) ---------------------------------------
create policy "brands_rw_own" on public.brands
  for all using (owner_user_id = auth.uid())
  with check (owner_user_id = auth.uid());

-- 5. brand_kit_files / brand_kit_assets / operate_projects (via owning brand) --
create policy "brand_kit_files_rw_own" on public.brand_kit_files
  for all using (brand_id in (select id from public.brands where owner_user_id = auth.uid()))
  with check (brand_id in (select id from public.brands where owner_user_id = auth.uid()));

create policy "brand_kit_assets_rw_own" on public.brand_kit_assets
  for all using (brand_id in (select id from public.brands where owner_user_id = auth.uid()))
  with check (brand_id in (select id from public.brands where owner_user_id = auth.uid()));

create policy "operate_projects_rw_own" on public.operate_projects
  for all using (brand_id in (select id from public.brands where owner_user_id = auth.uid()))
  with check (brand_id in (select id from public.brands where owner_user_id = auth.uid()));
